spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}
info:
  app.name: zuul
  company.name: tunyar.com
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
  routes:
    ucenter.serviceId: tunyar-ucenter
    ucenter.path: /ucenter/**
    shop.serviceId: tunyar-shop
    shop.path: /shop/**
  ignored-services: "*"
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}
info:
  app.name: zuul
  company.name: tunyar.com
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
  routes:
    ucenter.serviceId: tunyar-ucenter
    ucenter.path: /ucenter/**
    shop.serviceId: tunyar-shop
    shop.path: /shop/**
  ignored-services: "*"
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
